= Persisted Svelte Stores
:toc:
:!toc-placement:

This package exposes a store which is persisted to storage and has typescript support.

toc::[]

== Usage

Install the package:

.npm
[source,bash]
----
npm install @svelte-library/svelte-persistable
----

.yarn
[source,bash]
----
yarn add @svelte-library/svelte-persistable
----

=== 1. Define your store

.`src/myStore.ts`
[source,typescript]
----
import {persistable, Config, JsonTransformer} from '@svelte-library/svelte-persistable';

interface MyStore {
  message: string;
}

// a function which provides the default value.
// it is only executed when no value was found in store.
const getDefaultValue = (): MyStore => ({
  message: "Hello World!"
});

const storageConfig: Config<MyStore> = {
  // this key must be unique within your app as it is used to
  // persist the state
  key: 'myApp/myStore',
};

export const myStore = persistable<MyStore>(
  getDefaultValue,
  storageConfig
)
----

=== 2. Add a Gate to your app

A gate prevents your app from starting until the persistable stores are done loading:

.`src/App.svelte`
[source,sveltets]
----
<script lang="ts">
  import {Gate} from '@svelte-library/svelte-persistable';
  import {MessageDisplay} from './MessageDisplay.svelte';
  import {MessageInput} from './MessageInput.svelte';
  import {myStore} from './myStore';
</script>

<Gate waitFor={myStore}>
  <MessageDisplay />
  <MessageInput />
</Gate>
----

=== 3. Use the data from your store

You can use your store just like any other [readable](https://svelte.dev/tutorial/readable-stores):

.`src/MessageDisplay.svelte`
[source,sveltets]
----
<script lang="ts">
  import {myStore} from './myStore';
</script>

<p>Message: {$myStore.message}</p>
----

=== 4. Write to your store

And finally, you can use your store just like any other [writable](https://svelte.dev/tutorial/writable-stores).

.`src/MessageInput.svelte`
[source,scveltets]
----
<script lang="ts">
  import {myStore} from './myStore';
</script>

<input bind:value={$myStore.message}>
----

== API

=== `Config` object

This object contains the configuration of the <<_persistable_store>>.

|===
|Property |Type |Description

| `key`
| `string`
| A key which is unique within your application.
This key is used to store the data contained in the <<_persistable_store>>.

| `storage`
| <<_storage_interface>> (optional)
| This implementation is used to persist the data after it has changed,
and to load the data when the app is loaded.
This implementation may be asynchronous.
By default this is `window.localStorage`.

| `transform`
| <<_transform_interface>> (optional)
| This implementation is used to (de)serialize the data before it is going to the <<_storage_interface>>
and after it is coming from the <<_storage_interface>>.
By default this is using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify[`JSON.stringify`] and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse[`JSON.parse`].

|===

==== Example

=== `Gate` Component

==== Example

=== `persistable` store

==== Example

=== `Storage` interface

==== Example

=== `Transform` interface

==== Example
